/* ===============================================================
 * LA PUERTA ABIERTA — datos (versículos, oraciones, liturgia,
 * santos, salmos)
 *
 * Autor   : Emir Segovia
 * Año     : 2025
 *
 * No alterar el contenido bíblico ni litúrgico. No eliminar la
 * autoría. No redistribuir sin autorización de Emir Segovia
 * (emirvalles90@gmail.com).
 *
 * Fuente de las citas bíblicas: revisadas y corregidas según la
 * Biblia del sitio oficial de la Santa Sede — El Libro del Pueblo
 * de Dios: https://www.vatican.va/content/bibbia/es.html
 * =============================================================== */

const VS=[
  // TRISTEZA
  {a:'tristeza',c:'#6b8cba',t:'El Señor está cerca de los que tienen el corazón quebrantado, y salva a los de espíritu abatido.',r:'Salmos 34, 18',x:'El dolor no es abandono divino; Dios se acerca especialmente en el sufrimiento.'},
  {a:'tristeza',c:'#6b8cba',t:'Vengan a mí todos los que están fatigados y sobrecargados, y yo les daré descanso.',r:'Mateo 11, 28',x:'Jesús no pide que vengas cuando estés bien; llama precisamente al que carga con algo pesado.'},
  {a:'tristeza',c:'#6b8cba',t:'¿Por qué te abates, alma mía? ¿Por qué te agitas dentro de mí? Espera en Dios, pues he de alabarle todavía.',r:'Salmos 42, 11',x:'El salmista se habla a sí mismo en la angustia y se recuerda la esperanza.'},
  {a:'tristeza',c:'#6b8cba',t:'Él sana a los de corazón quebrantado y venda sus heridas.',r:'Salmos 147, 3',x:'Dios es el médico del alma; la sanación viene de arriba.'},
  {a:'tristeza',c:'#6b8cba',t:'Aunque cruce por oscuras quebradas, no temeré ningún mal, porque tú estás conmigo: tu vara y tu bastón me infunden confianza.',r:'Salmos 23, 4',x:'La oscuridad no es ausencia de Dios: Él camina junto al que atraviesa el dolor.'},
  {a:'tristeza',c:'#6b8cba',t:'Has cambiado mi luto en danza; quitaste mi lamento y me ceñiste de alegría.',r:'Salmos 30, 11',x:'La transformación del dolor en gozo es obra de Dios, no del tiempo solo.'},
  {a:'tristeza',c:'#6b8cba',t:'Los que sembraron con lágrimas cosecharán entre cantares.',r:'Salmos 126, 5',x:'Cada lágrima derramada con fe es semilla de una alegría futura.'},
  {a:'tristeza',c:'#6b8cba',t:'Dios secará las lágrimas de sus ojos: ya no habrá muerte, ni luto, ni llanto, ni dolor.',r:'Apocalipsis 21, 4',x:'La promesa última: Dios mismo secará cada lágrima con su propia mano.'},
  // ALEGRÍA
  {a:'alegria',c:'#c9a84c',t:'Este es el día que hizo el Señor; regocijémonos y alegrémonos en él.',r:'Salmos 118, 24',x:'Cada día es don divino y motivo de alabanza.'},
  {a:'alegria',c:'#c9a84c',t:'Alégrense siempre en el Señor. Vuelvo a insistir, alégrense.',r:'Filipenses 4, 4',x:'San Pablo escribe desde la cárcel: la alegría cristiana no depende de circunstancias.'},
  {a:'alegria',c:'#c9a84c',t:'El gozo del Señor es la fortaleza de ustedes.',r:'Nehemías 8, 10',x:'La alegría espiritual no es superficial: es fuente de fuerza interior.'},
  {a:'alegria',c:'#c9a84c',t:'Canten al Señor un cántico nuevo, porque ha hecho maravillas.',r:'Salmos 98, 1',x:'La alabanza es la respuesta natural del corazón que ha experimentado la gracia.'},
  {a:'alegria',c:'#c9a84c',t:'Me has dado a conocer los caminos de la vida; me llenarás de alegría con tu presencia.',r:'Hechos 2, 28',x:'La presencia de Dios es, en sí misma, fuente inagotable de gozo.'},
  {a:'alegria',c:'#c9a84c',t:'Regocíjense en el Señor siempre; otra vez lo digo: regocíjense.',r:'Filipenses 4, 4',x:'El imperativo de la alegría: no es opción sino vocación del cristiano.'},
  {a:'alegria',c:'#c9a84c',t:'Hasta ahora no han pedido nada en mi Nombre. Pidan y recibirán, y tendrán una alegría que será perfecta.',r:'Juan 16, 24',x:'Jesús desea que el gozo de sus discípulos sea completo, pleno, sin límites.'},
  {a:'alegria',c:'#c9a84c',t:'Les he dicho esto para que mi gozo sea el de ustedes, y ese gozo sea perfecto.',r:'Juan 15, 11',x:'El gozo de Jesús mismo quiere habitar en nosotros; esa es la promesa.'},
  // MIEDO
  {a:'miedo',c:'#8b6040',t:'No temas, porque yo estoy contigo, no te inquietes, porque yo soy tu Dios; yo te fortalezco y te ayudo, yo te sostengo con mi mano victoriosa.',r:'Isaías 41, 10',x:'Dios habla a Israel en el exilio. Su presencia es garantía contra el temor.'},
  {a:'miedo',c:'#8b6040',t:'El Señor es mi luz y mi salvación, ¿a quién temeré? El Señor es el baluarte de mi vida, ¿ante quién temblaré?',r:'Salmos 27, 1',x:'La fe en Dios transforma el miedo en confianza serena.'},
  {a:'miedo',c:'#8b6040',t:'No se angustien por nada, y en cualquier circunstancia recurran a la oración y a la súplica, acompañadas de acción de gracias, para presentar sus peticiones a Dios.',r:'Filipenses 4, 6',x:'La oración es el antídoto divino contra la ansiedad.'},
  {a:'miedo',c:'#8b6040',t:'En el amor no hay lugar para el temor: al contrario, el amor perfecto elimina el temor.',r:'1 Juan 4, 18',x:'El amor de Dios, cuando se acoge plenamente, disuelve el miedo.'},
  {a:'miedo',c:'#8b6040',t:'Si cruzas por las aguas, yo estaré contigo, y los ríos no te anegarán; si caminas por el fuego, no te quemarás, y las llamas no te abrasarán.',r:'Isaías 43, 2',x:'Dios no promete que no habrá tormentas; promete que no te hundirás en ellas.'},
  {a:'miedo',c:'#8b6040',t:'No temas, cree solamente.',r:'Marcos 5, 36',x:'Jesús lo dice en el momento más oscuro: cuando todo parece perdido, la fe es el único camino.'},
  {a:'miedo',c:'#8b6040',t:'Descarguen en él toda su preocupación, porque él tiene cuidado de ustedes.',r:'1 Pedro 5, 7',x:'La ansiedad no es para cargarla solo: puede depositarse en Dios, que cuida con ternura.'},
  // ESPERANZA
  {a:'esperanza',c:'#4a8c6b',t:'Yo conozco muy bien los planes que tengo proyectados sobre ustedes —oráculo del Señor—: son planes de prosperidad y no de desgracia, para asegurarles un porvenir y una esperanza.',r:'Jeremías 29, 11',x:'Dios habla al pueblo en el exilio: hay futuro aunque hoy no se vea.'},
  {a:'esperanza',c:'#4a8c6b',t:'Los que esperan en el Señor renuevan sus fuerzas, despliegan alas como las águilas; corren y no se agotan, avanzan y no se fatigan.',r:'Isaías 40, 31',x:'La esperanza no es pasividad: transforma y fortalece a quien la vive.'},
  {a:'esperanza',c:'#4a8c6b',t:'La esperanza no quedará defraudada, porque el amor de Dios ha sido derramado en nuestros corazones por el Espíritu Santo, que nos ha sido dado.',r:'Romanos 5, 5',x:'San Pablo enseña que la esperanza cristiana tiene fundamento sólido: el amor de Dios.'},
  {a:'esperanza',c:'#4a8c6b',t:'Yo lo puedo todo en aquel que me conforta.',r:'Filipenses 4, 13',x:'La fortaleza cristiana no viene de uno mismo sino de la comunión con Cristo.'},
  {a:'esperanza',c:'#4a8c6b',t:'Bendito el hombre que confía en el Señor, y cuya confianza es el Señor. Será como el árbol plantado junto a las aguas.',r:'Jeremías 17, 7-8',x:'La confianza en Dios da raíces profundas que resisten cualquier sequía o tormenta.'},
  {a:'esperanza',c:'#4a8c6b',t:'Tengo la certeza de que ni la muerte ni la vida, ni los ángeles ni los principados, ni lo presente ni lo futuro, ni ninguna otra criatura podrá separarnos jamás del amor de Dios, manifestado en Cristo Jesús, nuestro Señor.',r:'Romanos 8, 38-39',x:'La promesa más absoluta de San Pablo: nada en el universo puede romper ese amor.'},
  {a:'esperanza',c:'#4a8c6b',t:'El que comenzó en ustedes esta buena obra, la llevará a su cumplimiento hasta el día de Cristo Jesús.',r:'Filipenses 1, 6',x:'Dios no abandona lo que empieza: la obra de gracia en cada persona llegará a su plenitud.'},
  {a:'esperanza',c:'#4a8c6b',t:'Busquen primero el Reino de Dios y su justicia, y todo lo demás se les dará por añadidura.',r:'Mateo 6, 33',x:'La prioridad de Dios no deja al hombre sin lo necesario; la confianza tiene su fruto.'},
  // SOLEDAD
  {a:'soledad',c:'#7a6aac',t:'Aunque mi padre y mi madre me abandonen, el Señor me recibirá.',r:'Salmos 27, 10',x:'Incluso el abandono más doloroso no puede separarnos del amor de Dios.'},
  {a:'soledad',c:'#7a6aac',t:'Yo estoy con ustedes todos los días, hasta el fin del mundo.',r:'Mateo 28, 20',x:'Las últimas palabras de Jesús en Mateo son una promesa de compañía permanente.'},
  {a:'soledad',c:'#7a6aac',t:'¿Puede una madre olvidarse de su criatura? Aunque ella se olvidase, yo no te olvidaré.',r:'Isaías 49, 15',x:'Dios usa la imagen del amor materno para hablar de su fidelidad absoluta.'},
  {a:'soledad',c:'#7a6aac',t:'Yo estoy junto a la puerta y llamo: si alguien oye mi voz y me abre, entraré en su casa y cenaremos juntos.',r:'Apocalipsis 3, 20',x:'Jesús llama a la puerta del corazón: nadie que abra queda solo ni sin compañía.'},
  {a:'soledad',c:'#7a6aac',t:'¿A dónde iré para estar lejos de tu espíritu? ¿A dónde huiré de tu presencia?',r:'Salmos 139, 7',x:'No existe lugar, interior o exterior, donde Dios no esté. La soledad absoluta es imposible para el creyente.'},
  {a:'soledad',c:'#7a6aac',t:'No te dejaré ni te abandonaré.',r:'Josué 1, 5',x:'La promesa que Dios repite a lo largo de toda la Biblia: su presencia es permanente.'},
  // GRATITUD
  {a:'gratitud',c:'#b8860b',t:'Den gracias al Señor, porque es bueno, porque es eterna su misericordia.',r:'Salmos 136, 1',x:'El estribillo se repite 26 veces: la misericordia divina es inagotable.'},
  {a:'gratitud',c:'#b8860b',t:'Den gracias en toda ocasión, porque esta es la voluntad de Dios para ustedes en Cristo Jesús.',r:'1 Tesalonicenses 5, 18',x:'La gratitud no es solo por las cosas buenas: es actitud permanente del alma cristiana.'},
  {a:'gratitud',c:'#b8860b',t:'¿Qué pagaré al Señor por todos sus beneficios para conmigo?',r:'Salmos 116, 12',x:'El reconocimiento de los dones recibidos es el comienzo de la vida espiritual madura.'},
  {a:'gratitud',c:'#b8860b',t:'Bendice al Señor, alma mía, y nunca olvides sus beneficios.',r:'Salmos 103, 2',x:'El olvido es el enemigo de la gratitud; recordar los dones es un acto espiritual.'},
  {a:'gratitud',c:'#b8860b',t:'Sean agradecidos en toda circunstancia: esta es la voluntad de Dios en Cristo Jesús para con ustedes.',r:'1 Tesalonicenses 5, 18',x:'La gratitud en toda circunstancia revela un corazón que confía más allá de lo que ve.'},
  {a:'gratitud',c:'#b8860b',t:'¡Cuán preciosos me son, oh Dios, tus pensamientos! ¡Cuán grande es la suma de ellos!',r:'Salmos 139, 17',x:'Maravillarse ante Dios es la forma más elevada de gratitud.'},
  // FORTALEZA
  {a:'fortaleza',c:'#8b2020',t:'¡Sean fuertes y valientes! No tengan miedo ni tiemblen, porque el Señor, tu Dios, te acompaña, y él no te abandonará ni te dejará desamparado.',r:'Deuteronomio 31, 6',x:'Moisés despide al pueblo con estas palabras antes de su muerte.'},
  {a:'fortaleza',c:'#8b2020',t:'Fortalézcanse en el Señor y en la fuerza de su poder.',r:'Efesios 6, 10',x:'San Pablo invita a no apoyarse en la fuerza propia sino en la de Dios.'},
  {a:'fortaleza',c:'#8b2020',t:'El Señor es mi fortaleza y mi escudo; en él confía mi corazón.',r:'Salmos 28, 7',x:'La imagen de Dios como escudo y roca aparece repetidamente en los Salmos.'},
  {a:'fortaleza',c:'#8b2020',t:'El que persevere hasta el fin, se salvará.',r:'Mateo 24, 13',x:'La perseverancia en la fe, no la perfección, es lo que Jesús pide.'},
  {a:'fortaleza',c:'#8b2020',t:'No nos cansemos de hacer el bien; porque a su tiempo segaremos, si no desmayamos.',r:'Gálatas 6, 9',x:'La cosecha del bien viene para el que no abandona, aunque el resultado tarde en verse.'},
  {a:'fortaleza',c:'#8b2020',t:'Mi gracia es suficiente para ti; porque mi poder se perfecciona en la debilidad.',r:'2 Corintios 12, 9',x:'Dios obra con más poder donde el hombre reconoce que no puede solo.'},
  {a:'fortaleza',c:'#8b2020',t:'¿Acaso no soy yo el que te ordeno que seas fuerte y valiente? No temas ni te acobardes, porque el Señor, tu Dios, estará contigo dondequiera que vayas.',r:'Josué 1, 9',x:'La valentía bíblica no es ausencia de miedo: es avanzar sabiendo que Dios acompaña.'},
  // PAZ
  {a:'paz',c:'#4a8c8c',t:'Les dejo la paz, les doy mi paz, pero no como la da el mundo.',r:'Juan 14, 27',x:'Jesús distingue su paz de la paz mundana: es don interior que no depende de circunstancias.'},
  {a:'paz',c:'#4a8c8c',t:'La paz de Dios, que supera todo lo que podemos pensar, tomará bajo su cuidado los corazones y los pensamientos de ustedes en Cristo Jesús.',r:'Filipenses 4, 7',x:'Una paz que supera la comprensión racional: es don sobrenatural.'},
  {a:'paz',c:'#4a8c8c',t:'Felices los que trabajan por la paz, porque serán llamados hijos de Dios.',r:'Mateo 5, 9',x:'De las Bienaventuranzas: la paz no solo se recibe, también se construye.'},
  {a:'paz',c:'#4a8c8c',t:'Tú guardarás en completa paz a aquel cuyo pensamiento en ti persevera, porque en ti ha confiado.',r:'Isaías 26, 3',x:'La paz interior nace de mantener la mente anclada en Dios, no en las circunstancias.'},
  {a:'paz',c:'#4a8c8c',t:'¡Que no se inquiete el corazón de ustedes, ni tengan miedo!',r:'Juan 14, 27',x:'Jesús habla horas antes de su muerte: la serenidad que ofrece va más allá de cualquier tormenta.'},
  {a:'paz',c:'#4a8c8c',t:'En el mundo tendrán que sufrir; pero tengan valor: yo he vencido al mundo.',r:'Juan 16, 33',x:'Jesús no promete ausencia de dificultades sino la certeza de una victoria ya alcanzada.'},
  // PERDÓN
  {a:'perdon',c:'#6b4c8c',t:'El Señor es bondadoso y compasivo, lento para enojarse y de gran misericordia.',r:'Salmos 103, 8',x:'Uno de los textos más bellos sobre la misericordia divina en el Antiguo Testamento.'},
  {a:'perdon',c:'#6b4c8c',t:'Si confesamos nuestros pecados, él es fiel y justo: nos los perdonará.',r:'1 Juan 1, 9',x:'La confesión sincera encuentra siempre la misericordia de Dios.'},
  {a:'perdon',c:'#6b4c8c',t:'Perdónense mutuamente, como Dios los perdonó en Cristo.',r:'Efesios 4, 32',x:'El perdón humano tiene su modelo y su fuente en el perdón divino.'},
  {a:'perdon',c:'#6b4c8c',t:'¿Qué Dios como tú, que perdona la maldad y olvida el pecado del remanente de su heredad?',r:'Miqueas 7, 18',x:'El profeta se asombra ante un Dios que no solo perdona sino que olvida.'},
  {a:'perdon',c:'#6b4c8c',t:'Aunque sus pecados sean como la grana, quedarán blancos como la nieve.',r:'Isaías 1, 18',x:'La imagen es total: el color más difícil de quitar, convertido en la blancura más pura.'},
  {a:'perdon',c:'#6b4c8c',t:'Feliz aquel cuya falta ha sido perdonada, cuyo pecado ha sido borrado.',r:'Salmos 32, 1',x:'David canta la dicha del perdón recibido: la culpa cubierta es el comienzo de la paz.'},
  {a:'perdon',c:'#6b4c8c',t:'Como el Padre me amó, también yo los he amado a ustedes. Permanezcan en mi amor.',r:'Juan 15, 9',x:'El amor de Jesús es la fuente del perdón: permanecer en ese amor es la vida cristiana.'},
  // FE
  {a:'fe',c:'#4a7a8c',t:'La fe es la garantía de los bienes que se esperan, la plena certeza de las realidades que no se ven.',r:'Hebreos 11, 1',x:'La definición clásica de la fe: certeza de lo invisible, fundamento de la esperanza.'},
  {a:'fe',c:'#4a7a8c',t:'Sin fe es imposible agradar a Dios, pues quien se acerca a Dios debe creer que existe.',r:'Hebreos 11, 6',x:'La fe es la condición básica de la relación con Dios.'},
  {a:'fe',c:'#4a7a8c',t:'Dios amó tanto al mundo, que entregó a su Hijo único para que todo el que cree en él no muera, sino que tenga Vida eterna.',r:'Juan 3, 16',x:'El versículo más conocido del Evangelio: síntesis del mensaje cristiano.'},
  {a:'fe',c:'#4a7a8c',t:'Todo es posible para el que cree.',r:'Marcos 9, 23',x:'Jesús lo dice ante un caso humanamente desesperado: la fe abre lo que la razón cierra.'},
  {a:'fe',c:'#4a7a8c',t:'El justo vivirá por la fe.',r:'Romanos 1, 17',x:'El principio central de San Pablo: la vida auténtica brota de la fe, no de las obras solas.'},
  {a:'fe',c:'#4a7a8c',t:'Si tienen fe del tamaño de un grano de mostaza, podrán decirle a este monte: "Trasládate de aquí para allá", y se trasladará.',r:'Mateo 17, 20',x:'No la cantidad sino la calidad y autenticidad de la fe es lo que mueve montañas.'},
  {a:'fe',c:'#4a7a8c',t:'Yo estoy junto a la puerta y llamo: si alguien oye mi voz y me abre, entraré en su casa.',r:'Apocalipsis 3, 20',x:'La fe comienza con un acto de apertura: escuchar, reconocer, abrir.'},
  // AMOR
  {a:'amor',c:'#c06080',t:'Amarás al Señor, tu Dios, con todo tu corazón, con toda tu alma y con toda tu mente. Este es el mandamiento más grande y el primero.',r:'Mateo 22, 37-38',x:'Jesús resume toda la ley en el amor: primero a Dios, y de ahí todo lo demás.'},
  {a:'amor',c:'#c06080',t:'En esto reconocerán todos que ustedes son mis discípulos: en el amor que se tengan los unos a los otros.',r:'Juan 13, 35',x:'El amor entre cristianos es la señal que identifica al discípulo, no los títulos ni las palabras.'},
  {a:'amor',c:'#c06080',t:'El amor es paciente, es servicial; el amor no es envidioso, no hace alarde, no se envanece.',r:'1 Corintios 13, 4',x:'El himno al amor de San Pablo: no es un sentimiento sino una forma concreta de vivir.'},
  {a:'amor',c:'#c06080',t:'No hay amor más grande que dar la vida por los amigos.',r:'Juan 15, 13',x:'Jesús define el amor máximo que Él mismo realizará horas después.'},
  {a:'amor',c:'#c06080',t:'El amor cubre multitud de pecados.',r:'1 Pedro 4, 8',x:'El amor no ignora el pecado; lo transforma, cura, reconcilia.'},
  {a:'amor',c:'#c06080',t:'Dios es amor, y el que permanece en el amor permanece en Dios, y Dios permanece en él.',r:'1 Juan 4, 16',x:'La definición más profunda de Dios en toda la Escritura: no que ama, sino que ES amor.'},
  // CONFIANZA
  {a:'confianza',c:'#7a9a6a',t:'Confía en el Señor con todo tu corazón, y no te apoyes en tu propia inteligencia.',r:'Proverbios 3, 5',x:'La sabiduría bíblica enseña que la inteligencia humana necesita un fundamento más alto.'},
  {a:'confianza',c:'#7a9a6a',t:'El Señor es mi pastor, nada me puede faltar.',r:'Salmos 23, 1',x:'La imagen del pastor: alguien que conoce por nombre a cada oveja y la cuida con ternura.'},
  {a:'confianza',c:'#7a9a6a',t:'Encomienda al Señor tu camino, confía en él, y él actuará.',r:'Salmos 37, 5',x:'La confianza no es pasividad: es dejar que Dios actúe mientras uno da los pasos que puede.'},
  {a:'confianza',c:'#7a9a6a',t:'La misericordia del Señor dura por siempre, para los que lo temen.',r:'Salmos 103, 17',x:'La misericordia de Dios no tiene principio ni fin: es el fundamento más firme de la confianza.'},
];

const CARDS=[
  {tema:'tristeza',c:'#6b8cba',l:'Tristeza',q:'"El Señor está cerca de los que tienen el corazón quebrantado." — Salmos 34, 18',a:'En la tradición bíblica, el corazón quebrantado no es debilidad a superar sino la disposición que más atrae la presencia de Dios. La tristeza sincera puede ser un umbral hacia lo sagrado.',h:'La tristeza puede ser el momento más cercano a Dios.'},
  {tema:'tristeza',c:'#6b8cba',l:'Tristeza',q:'"Vengan a mí todos los que están fatigados y sobrecargados, y yo les daré descanso." — Mateo 11, 28',a:'Jesús no pide que vengas cuando estés bien. Llama precisamente a los cargados. El descanso que ofrece no es ausencia de problemas sino una presencia que sostiene en medio de ellos.',h:'La invitación de Jesús va dirigida específicamente al que sufre.'},
  {tema:'alegria',c:'#c9a84c',l:'Alegría',q:'"Alégrense siempre en el Señor. Vuelvo a insistir, alégrense." — Filipenses 4, 4',a:'San Pablo escribía estas palabras desde la prisión. La alegría cristiana no nace de las circunstancias externas sino de la comunión con Cristo. Por eso puede mandarse como virtud.',h:'La alegría de la fe se puede cultivar como virtud, no depende del estado de ánimo.'},
  {tema:'alegria',c:'#c9a84c',l:'Alegría',q:'"El gozo del Señor es la fortaleza de ustedes." — Nehemías 8, 10',a:'En la renovación del pacto tras el exilio, Esdras llama al pueblo al gozo. La alegría espiritual no es superficial: es fuente de resistencia y fuerza para vivir con integridad.',h:'Alegría y fortaleza están unidos: el gozo interior sostiene en las dificultades.'},
  {tema:'miedo',c:'#8b6040',l:'Miedo',q:'"No temas, porque yo estoy contigo; no te inquietes, porque yo soy tu Dios." — Isaías 41, 10',a:'Las palabras "no temas" aparecen más de 300 veces en la Biblia. Dios no promete ausencia de peligro sino su presencia en el peligro. La cercanía divina transforma el miedo.',h:'"No temas" es el mandato más repetido en la Biblia — presencia, no ausencia del peligro.'},
  {tema:'miedo',c:'#8b6040',l:'Miedo',q:'"En el amor no hay lugar para el temor: el amor perfecto elimina el temor." — 1 Juan 4, 18',a:'San Juan enseña que el miedo y el amor operan en el alma de modo inverso. Crecer en el amor de Dios y al prójimo es el camino para vencer el temor desde adentro, no reprimiéndolo.',h:'El miedo se vence creciendo en el amor, no suprimiéndolo por voluntad.'},
  {tema:'esperanza',c:'#4a8c6b',l:'Esperanza',q:'"Los que esperan en el Señor renuevan sus fuerzas, despliegan alas como las águilas." — Isaías 40, 31',a:'El águila no vuela por su propia fuerza sino aprovechando las corrientes de aire. Así la esperanza: no es autoconfianza sino apertura a la fuerza de Dios que nos levanta.',h:'Esperar en el Señor es como el águila: no fuerza propia sino apertura a la corriente divina.'},
  {tema:'esperanza',c:'#4a8c6b',l:'Esperanza',q:'"La esperanza no quedará defraudada, porque el amor de Dios ha sido derramado en nuestros corazones." — Romanos 5, 5',a:'San Pablo distingue la esperanza cristiana del optimismo humano. El optimismo puede decepcionar; la esperanza cristiana se asienta en el amor de Dios que ya actúa en el corazón.',h:'La esperanza cristiana no es optimismo: tiene fundamento real — el amor ya presente.'},
  {tema:'fortaleza',c:'#8b2020',l:'Fortaleza',q:'"Yo lo puedo todo en aquel que me conforta." — Filipenses 4, 13',a:'Una de las frases más malinterpretadas: no significa que el cristiano puede hacer todo lo que quiera. Significa que en la comunión con Cristo hay fuerza para aceptar toda situación con serenidad.',h:'El contexto es clave: Pablo habla de aceptar toda situación, no de logros ilimitados.'},
  {tema:'fortaleza',c:'#8b2020',l:'Fortaleza',q:'"Sean fuertes y valientes. No teman, porque el Señor, su Dios, los acompaña." — Deuteronomio 31, 6',a:'Las últimas palabras de Moisés antes de su muerte. La valentía que pide no es la del héroe solitario sino la del que sabe que no está solo. La presencia de Dios transforma la debilidad.',h:'La valentía bíblica no es ausencia de miedo sino la decisión de actuar apoyándose en Dios.'},
  {tema:'paz',c:'#4a8c8c',l:'Paz',q:'"Les dejo la paz, les doy mi paz, pero no como la da el mundo." — Juan 14, 27',a:'Jesús distingue dos paces. La del mundo es frágil: depende de circunstancias favorables. Su paz es interior, no depende de las condiciones externas ni de la comprensión humana.',h:'La paz de Cristo no es ausencia de conflicto sino presencia interior que sostiene en él.'},
  {tema:'paz',c:'#4a8c8c',l:'Paz',q:'"Felices los que trabajan por la paz, porque serán llamados hijos de Dios." — Mateo 5, 9',a:'La paz no es solo algo que se recibe pasivamente: se construye activamente. Trabajar por la paz es tarea que revela la filiación divina. El que hace la paz se parece a Dios.',h:'La paz se construye, no solo se recibe. Los artesanos de paz son imagen de Dios.'},
];
const LITURGIA=[
  {color:'#4a5c8c',n:'Adviento',d:'Preparación y espera · Color morado',i:'El Adviento es el tiempo de preparación para la Navidad y de espera de la segunda venida de Cristo. Comienza el 4º domingo antes del 25 de diciembre. El color litúrgico es el morado (penitencia y espera), excepto el 3er domingo "Gaudete" (rosa). Dura entre 22 y 28 días.',cl:'Morado / Rosa (3er domingo)',fechas:[
    {d:'1er domingo de Adviento',n:'Inicio del Adviento',nota:'{{FECHA_ADVIENTO}}'},
    {d:'8 de diciembre',n:'Inmaculada Concepción',nota:'Solemnidad. Dogma definido en 1854 por Pío IX'},
    {d:'3er domingo',n:'Domingo Gaudete',nota:'Color rosa. "Alegraos" (Flp 4,4)'},
    {d:'17–24 diciembre',n:'Antífonas "O"',nota:'Siete días de intensa preparación'},
  ]},
  {color:'#c9a84c',n:'Navidad y Epifanía',d:'El misterio de la Encarnación · Color blanco/dorado',i:'El tiempo de Navidad celebra la Encarnación del Hijo de Dios. Comienza en las Vísperas del 24 de diciembre y se extiende hasta el Bautismo del Señor. El color es blanco o dorado, símbolo de alegría y gloria.',cl:'Blanco / Dorado',fechas:[
    {d:'24 de diciembre (noche)',n:'Misa de Gallo',nota:'Inicio de la Navidad'},
    {d:'25 de diciembre',n:'Natividad del Señor',nota:'Solemnidad mayor. Tres misas posibles.'},
    {d:'26 de diciembre',n:'San Esteban Protomártir',nota:'Primer mártir cristiano. Fiesta'},
    {d:'28 de diciembre',n:'Santos Inocentes',nota:'Mártires por Cristo sin saberlo. Fiesta'},
    {d:'1 de enero',n:'Santa María, Madre de Dios',nota:'Solemnidad. Jornada Mundial de la Paz'},
    {d:'6 de enero',n:'Epifanía del Señor',nota:'Manifestación a los Magos. Solemnidad'},
    {d:'Dom. después Epifanía',n:'Bautismo del Señor',nota:'Cierra el tiempo de Navidad'},
  ]},
  {color:'#4a7a4a',n:'Tiempo Ordinario (I)',d:'Semanas 1 a 8 · Color verde',i:'El Tiempo Ordinario es el período donde se medita la vida pública de Jesús. El color verde simboliza la esperanza y el crecimiento espiritual. La primera parte va desde el Bautismo del Señor hasta el Miércoles de Ceniza.',cl:'Verde',fechas:[
    {d:'2 de febrero',n:'Presentación del Señor',nota:'Fiesta. 40 días después de Navidad. "La Candelaria"'},
    {d:'Variable (antes Cuaresma)',n:'Martes de Carnaval',nota:'Último día antes del Miércoles de Ceniza'},
    {d:'Variable',n:'Miércoles de Ceniza',nota:'{{FECHA_CENIZA}}. Inicio de la Cuaresma'},
  ]},
  {color:'#6b3a6b',n:'Cuaresma',d:'40 días de conversión · Color morado',i:'La Cuaresma es el tiempo de conversión, penitencia y preparación para la Pascua. Dura 40 días (sin contar domingos) en recuerdo de los 40 años en el desierto y los 40 días de ayuno de Jesús. Comienza el Miércoles de Ceniza.',cl:'Morado / Rosa (4to domingo)',fechas:[
    {d:'Miércoles de Ceniza',n:'Inicio de la Cuaresma',nota:'{{FECHA_CENIZA}}'},
    {d:'2° domingo',n:'Transfiguración del Señor',nota:'Anticipo de la gloria pascual'},
    {d:'4° domingo',n:'Domingo Laetare',nota:'Color rosa. "Alégrate, Jerusalén"'},
    {d:'5° domingo',n:'Domingo de Pasión',nota:'Se recuerda el inicio de la Pasión'},
    {d:'Domingo antes de Pascua',n:'Domingo de Ramos',nota:'Inicio de la Semana Santa. Se bendicen palmas'},
  ]},
  {color:'#8b1a1a',n:'Triduo Pascual y Pascua',d:'El corazón del año cristiano · Color rojo/blanco',i:'El Triduo Pascual —Jueves, Viernes y Sábado Santos— es el corazón de todo el año litúrgico. En él se celebra el misterio central del cristianismo: la muerte y resurrección de Cristo. El tiempo pascual dura 50 días hasta Pentecostés.',cl:'Rojo (Semana Santa) / Blanco (Pascua)',fechas:[
    {d:'Jueves Santo',n:'Misa de la Cena del Señor',nota:'Institución de la Eucaristía y el sacerdocio. Lavatorio de pies'},
    {d:'Viernes Santo',n:'Pasión del Señor',nota:'Única celebración sin Eucaristía. Adoración de la Cruz'},
    {d:'Sábado Santo',n:'Vigilia Pascual',nota:'La madre de todas las vigilias. Fuego nuevo, Exultet, bautismos'},
    {d:'Domingo de Pascua',n:'Resurrección del Señor',nota:'{{FECHA_PASCUA}}. Solemnidad de solemnidades'},
    {d:'2° domingo de Pascua',n:'Divina Misericordia',nota:'Instituida por San Juan Pablo II en 2000'},
    {d:'40 días después',n:'Ascensión del Señor',nota:'Solemnidad. En muchos países: 7° domingo de Pascua'},
    {d:'50 días después',n:'Pentecostés',nota:'{{FECHA_PENTECOSTES}}. Venida del Espíritu Santo'},
  ]},
  {color:'#4a6c8c',n:'Tiempo Ordinario (II) y Solemnidades',d:'Pentecostés al fin del año · Color verde/blanco',i:'La segunda parte del Tiempo Ordinario va desde Pentecostés hasta el final del año litúrgico. Incluye grandes solemnidades que enriquecen el camino de la Iglesia.',cl:'Verde / Blanco (solemnidades)',fechas:[
    {d:'Dom. después Pentecostés',n:'Santísima Trinidad',nota:'Solemnidad. Misterio central de la fe cristiana'},
    {d:'Jueves después Trinidad',n:'Corpus Christi',nota:'Cuerpo y Sangre de Cristo. Procesiones eucarísticas'},
    {d:'24 de junio',n:'Natividad de San Juan Bautista',nota:'Solemnidad. Único santo cuyo nacimiento se celebra (además de María y Jesús)'},
    {d:'29 de junio',n:'Santos Pedro y Pablo',nota:'Solemnidad. Pilares de la Iglesia'},
    {d:'15 de agosto',n:'Asunción de la Virgen María',nota:'Solemnidad. Dogma definido en 1950 por Pío XII'},
    {d:'1 de noviembre',n:'Todos los Santos',nota:'Solemnidad. La Iglesia triunfante'},
    {d:'2 de noviembre',n:'Fieles Difuntos',nota:'Por las almas del purgatorio'},
    {d:'Último domingo',n:'Cristo Rey del Universo',nota:'Cierra el año litúrgico. Solemnidad'},
  ]},
];
const ORACIONES=[
  {t:'Señal de la Cruz',tp:'Invocación Trinitaria',o:'Tradición apostólica. Abre y cierra toda oración católica.',tx:'En el nombre del Padre,\ny del Hijo,\ny del Espíritu Santo.\nAmén.'},
  {t:'Padre Nuestro',tp:'Oración del Señor',o:'Mateo 6, 9-13 — La única oración enseñada por Jesús mismo',tx:'Padre nuestro, que estás en el cielo,\nsantificado sea tu Nombre;\nvenga a nosotros tu Reino;\nhágase tu voluntad\nen la tierra como en el cielo.\nDanos hoy nuestro pan de cada día;\nperdona nuestras ofensas,\ncomo también nosotros perdonamos\na los que nos ofenden;\nno nos dejes caer en la tentación,\ny líbranos del mal. Amén.'},
  {t:'Ave María',tp:'Oración Mariana',o:'Lucas 1, 28.42 y tradición de la Iglesia — Oración más rezada del mundo',tx:'Dios te salve, María,\nllena eres de gracia;\nel Señor es contigo.\nBendita tú eres entre todas las mujeres\ny bendito es el fruto de tu vientre, Jesús.\n\nSanta María, Madre de Dios,\nruega por nosotros, pecadores,\nahora y en la hora de nuestra muerte. Amén.'},
  {t:'Gloria al Padre',tp:'Doxología Trinitaria',o:'Tradición apostólica. Se reza al final de cada misterio del Rosario.',tx:'Gloria al Padre,\ny al Hijo,\ny al Espíritu Santo.\nComo era en el principio,\nahora y siempre,\ny por los siglos de los siglos. Amén.'},
  {t:'Oh Jesús mío',tp:'Oración de Fátima',o:'Pedida por la Virgen a los pastorcitos de Fátima en 1917. Se reza después del Gloria de cada decena del Rosario.',tx:'Oh Jesús mío,\nperdona nuestros pecados,\nlíbranos del fuego del infierno,\nlleva al cielo a todas las almas,\nespecialmente a las más necesitadas de tu misericordia. Amén.'},
  {t:'Credo Apostólico',tp:'Profesión de Fe',o:'Síntesis de la fe de los apóstoles. Se usa en el Bautismo y el Rosario.',tx:'Creo en Dios, Padre todopoderoso,\nCreador del cielo y de la tierra.\n\nCreo en Jesucristo, su único Hijo, nuestro Señor,\nque fue concebido por obra y gracia del Espíritu Santo,\nnació de Santa María Virgen,\npadeció bajo el poder de Poncio Pilato,\nfue crucificado, muerto y sepultado,\ndescendió a los infiernos,\nal tercer día resucitó de entre los muertos,\nsubió a los cielos\ny está sentado a la derecha de Dios, Padre todopoderoso.\nDesde allí ha de venir a juzgar a vivos y muertos.\n\nCreo en el Espíritu Santo,\nla santa Iglesia católica,\nla comunión de los santos,\nel perdón de los pecados,\nla resurrección de la carne\ny la vida eterna. Amén.'},
  {t:'Salve Regina',tp:'Antífona Mariana',o:'Siglo XI. Se reza al finalizar el Rosario y en la Liturgia de las Horas.',tx:'Dios te salve, Reina y Madre de misericordia,\nvida, dulzura y esperanza nuestra; Dios te salve.\nA ti clamamos los desterrados hijos de Eva;\na ti suspiramos, gimiendo y llorando\nen este valle de lágrimas.\n\nEa, pues, Señora, abogada nuestra,\nvuelve a nosotros esos tus ojos misericordiosos;\ny después de este destierro, muéstranos a Jesús,\nfruto bendito de tu vientre.\n\nOh clementísima, oh piadosa,\noh dulce Virgen María. Amén.'},
  {t:'Ángelus',tp:'Oración del Mediodía',o:'Tradición medieval. Se reza a las 6, 12 y 18 h al tañido de las campanas.',tx:'El ángel del Señor anunció a María,\ny ella concibió por obra del Espíritu Santo.\n— Dios te salve María... (Ave María)\n\nHe aquí la esclava del Señor,\nhágase en mí según tu palabra.\n— Dios te salve María... (Ave María)\n\nY el Verbo se hizo carne\ny habitó entre nosotros.\n— Dios te salve María... (Ave María)\n\nRuega por nosotros, Santa Madre de Dios,\npara que seamos dignos de alcanzar\nlas promesas de Jesucristo.\n\nOremos: Derrama, Señor, tu gracia sobre nosotros,\nque hemos conocido, por el anuncio del ángel,\nla Encarnación de tu Hijo Jesucristo,\npara que lleguemos por su Pasión y su Cruz\na la gloria de la Resurrección.\nPor Jesucristo Nuestro Señor. Amén.'},
  {t:'Oración de San Francisco',tp:'Oración de Paz',o:'Atribuida a San Francisco de Asís (s. XIII). Una de las oraciones más conocidas del mundo.',tx:'Señor, hazme instrumento de tu paz.\nDonde haya odio, lleve yo el amor;\ndonde haya ofensa, el perdón;\ndonde haya discordia, la unión;\ndonde haya duda, la fe;\ndonde haya error, la verdad;\ndonde haya desesperanza, la esperanza;\ndonde haya tristeza, la alegría;\ndonde haya sombras, tu luz.\n\nOh Divino Maestro,\nconcédeme que no busque tanto\nser consolado, como consolar;\nser comprendido, como comprender;\nser amado, como amar.\n\nPorque dando se recibe,\nolvidando se encuentra,\nperdonando se es perdonado,\ny muriendo se resucita a la vida eterna. Amén.'},
  {t:'Acto de Contrición',tp:'Oración Penitencial',o:'Tradición de la Iglesia. Se reza antes o después del Sacramento de la Reconciliación.',tx:'Dios mío,\nme arrepiento de todo corazón de todos mis pecados\ny los aborrezco,\nporque al pecar, no solo merezco las penas\nestablecidas por ti justamente,\nsino principalmente porque te ofendí a ti,\nsumo Bien y digno de amor por encima de todas las cosas.\n\nPor eso propongo firmemente,\ncon ayuda de tu gracia,\nno pecar más en adelante\ny huir de las ocasiones de pecado.\nAmén.'},
  {t:'Pésame',tp:'Acto de Contrición Popular',o:'Forma breve y tradicional del Acto de Contrición. Se reza al comienzo del Rosario, después de la Señal de la Cruz.',tx:'Pésame, Dios mío,\ny me arrepiento de todo corazón de haberos ofendido.\nPésame por el infierno que merecí\ny por el cielo que perdí;\npero mucho más me pesa,\nporque pecando ofendí a un Dios tan bueno y tan grande como Vos.\nAntes querría haber muerto que haberos ofendido,\ny propongo firmemente no pecar más\ny evitar todas las ocasiones próximas de pecado. Amén.'},
  {t:'Ofrecimiento del Rosario',tp:'Acto de Contrición y Ofrecimiento',o:'Tradición devocional. Se reza al comienzo del Rosario, después de la Señal de la Cruz, para ofrecerlo por una intención.',tx:'Dios mío, me arrepiento de todo corazón de todos mis pecados y los aborrezco,\nporque al pecar no solo merezco las penas que justamente estableciste,\nsino principalmente porque te ofendí, sumo Bien, que mereces todo mi amor.\n\nPor eso propongo firmemente, con la ayuda de tu gracia,\nno pecar más y evitar las ocasiones próximas de pecado.\n\nOfrezco este Santo Rosario por mis intenciones,\npor la Iglesia, por el Santo Padre y sus intenciones,\npor mi familia, por las personas que amo\ny por todas aquellas que necesitan de Dios.\n\nSanta María, Madre de Dios, ruega por nosotros. Amén.'},
  {t:'Oración final',tp:'Colecta del Rosario',o:'Oración tradicional con la que se cierra el rezo del Santo Rosario, después de la Salve.',tx:'Oh Dios, cuyo Hijo unigénito,\ncon su vida, muerte y resurrección,\nnos alcanzó el premio de la vida eterna;\n\nconcédenos que, meditando estos misterios\ndel Santísimo Rosario de la Virgen María,\nimitemos lo que contienen\ny alcancemos lo que prometen.\n\nPor el mismo Jesucristo, nuestro Señor. Amén.'},
  {t:'Sub Tuum Praesidium',tp:'Oración Mariana Antigua',o:'Siglo III d.C. Es la oración mariana más antigua conservada, hallada en un papiro egipcio de Oxirrinco.',tx:'Bajo tu amparo nos acogemos,\nSanta Madre de Dios.\nNo deseches las súplicas\nque te dirigimos en nuestras necesidades,\nantes bien líbranos siempre\nde todos los peligros,\noh Virgen gloriosa y bendita. Amén.'},
  {t:'Oración a San Miguel Arcángel',tp:'Oración de Protección',o:'Compuesta por el Papa León XIII en 1886. Se reza pidiendo protección contra el mal.',tx:'San Miguel Arcángel,\ndefiéndenos en la batalla;\nsé nuestro amparo\ncontra la perversidad y asechanzas del demonio.\n\nReprímalo Dios, pedimos suplicantes,\ny tú, Príncipe de la milicia celestial,\narroja al infierno con el divino poder\na Satanás y a los demás espíritus malignos\nque andan dispersos por el mundo\npara la perdición de las almas. Amén.'},
  {t:'Oración al Espíritu Santo',tp:'Oración de Pentecostés',o:'Veni Sancte Spiritus. Secuencia de Pentecostés, usada también antes de decisiones importantes.',tx:'Ven, Espíritu Santo,\nllena los corazones de tus fieles\ny enciende en ellos el fuego de tu amor.\n\nEnvía, Señor, tu Espíritu,\ny renueva la faz de la tierra.\n\nOremos: Oh Dios, que has instruido los corazones de los fieles\ncon la luz del Espíritu Santo,\nconcédenos que sepamos gustar del bien por el mismo Espíritu,\ny gozar siempre de sus divinos consuelos.\nPor Jesucristo, nuestro Señor. Amén.'},
  {t:'Oración a Santa Mónica',tp:'Oración por los Hijos',o:'Madre de San Agustín (s. IV). Patrona de las madres cristianas que ruegan por la conversión de sus hijos.',tx:'Señor, que a través de las lágrimas\ny la oración perseverante de Santa Mónica\nalcanzaste la conversión de su hijo Agustín,\nconcédenos, por su intercesión,\nla gracia de saber perseverar en la oración\npor nuestros seres queridos,\npara que también ellos encuentren tu camino.\n\nQue su ejemplo de paciencia, fe y amor maternal\nnos enseñe a no desfallecer nunca en la esperanza.\nPor Jesucristo, nuestro Señor. Amén.'},
  {t:'Oración a San Padre Pío',tp:'Oración de Intercesión',o:'San Pío de Pietrelcina (1887-1968), fraile capuchino que llevó los estigmas de Cristo.',tx:'Oh Dios, que adornaste al sacerdote San Pío\ncon la gracia singular de participar\nen la Pasión de tu Hijo,\nconcédenos, por su intercesión,\nque, unidos a Cristo crucificado,\nte sirvamos con caridad constante\npara alcanzar la gloria eterna.\n\nSan Pío, tú que llevaste en tu cuerpo\nlas llagas de Cristo,\nruega por nosotros,\npara que sepamos abrazar la cruz de cada día\ncon fe y amor. Por Jesucristo, nuestro Señor. Amén.'},
  {t:'Misterios del Santo Rosario',tp:'Guía de los Cuatro Misterios',o:'Los veinte episodios del Evangelio contemplados en el Rosario, agrupados de a cinco por día de la semana.',tx:'GOZOSOS (lunes y sábado)\nLa Anunciación del Ángel a María\nLa Visitación de María a su prima Isabel\nEl Nacimiento de Jesús en Belén\nLa Presentación de Jesús en el Templo\nEl Niño Jesús perdido y hallado en el Templo\n\nLUMINOSOS (jueves)\nEl Bautismo de Jesús en el Jordán\nLas Bodas de Caná\nEl anuncio del Reino de Dios y la llamada a la conversión\nLa Transfiguración del Señor\nLa Institución de la Eucaristía\n\nDOLOROSOS (martes y viernes)\nLa Oración de Jesús en el Huerto\nLa Flagelación del Señor atado a la columna\nLa Coronación de espinas\nJesús con la cruz a cuestas camino al Calvario\nLa Crucifixión y muerte de Jesús\n\nGLORIOSOS (miércoles y domingo)\nLa Resurrección del Señor\nLa Ascensión del Señor a los cielos\nLa Venida del Espíritu Santo sobre María y los Apóstoles\nLa Asunción de María al cielo\nLa Coronación de María como Reina del cielo y de la tierra'},
  {t:'Oración por los Difuntos',tp:'Oración de Sufragio',o:'Tradición litúrgica romana. Se reza recordando a los fieles difuntos, especialmente el 2 de noviembre.',tx:'Dales, Señor, el descanso eterno,\ny brille para ellos la luz perpetua.\nDescansen en paz. Amén.\n\nOremos: Te rogamos, Señor,\nque las almas de tus siervos difuntos,\npurificadas de sus pecados,\nalcancen la resurrección\ny la vida eterna en la gloria de tu Reino.\nPor Jesucristo, nuestro Señor. Amén.'},
  {t:'Oración por las Benditas Almas del Purgatorio',tp:'Oración de Sufragio',o:'Tradición devocional católica, ligada a la doctrina del Purgatorio y la comunión de los santos.',tx:'Oh Dios, Creador y Redentor de todos los fieles,\nconcede a las almas de tus siervos difuntos\nla remisión de todos sus pecados,\npara que alcancen, por nuestras piadosas súplicas,\nel perdón que siempre desearon.\n\nTú que vives y reinas por los siglos de los siglos. Amén.\n\nEterno descanso concédeles, Señor,\ny brille para ellas la luz perpetua.\nQue descansen en paz. Amén.'},
];
const MISTERIOS_ROSARIO={
  gozosos:{nombre:'Gozosos',dias:[1,6],diasTxt:'Lunes y sábado',lista:[
    'La Anunciación del Ángel a María',
    'La Visitación de María a su prima Isabel',
    'El Nacimiento de Jesús en Belén',
    'La Presentación de Jesús en el Templo',
    'El Niño Jesús perdido y hallado en el Templo',
  ]},
  dolorosos:{nombre:'Dolorosos',dias:[2,5],diasTxt:'Martes y viernes',lista:[
    'La Oración de Jesús en el Huerto',
    'La Flagelación del Señor atado a la columna',
    'La Coronación de espinas',
    'Jesús con la cruz a cuestas camino al Calvario',
    'La Crucifixión y muerte de Jesús',
  ]},
  gloriosos:{nombre:'Gloriosos',dias:[0,3],diasTxt:'Miércoles y domingo',lista:[
    'La Resurrección del Señor',
    'La Ascensión del Señor a los cielos',
    'La Venida del Espíritu Santo sobre María y los Apóstoles',
    'La Asunción de María al cielo',
    'La Coronación de María como Reina del cielo y de la tierra',
  ]},
  luminosos:{nombre:'Luminosos',dias:[4],diasTxt:'Jueves',lista:[
    'El Bautismo de Jesús en el Jordán',
    'Las Bodas de Caná',
    'El anuncio del Reino de Dios y la llamada a la conversión',
    'La Transfiguración del Señor',
    'La Institución de la Eucaristía',
  ]},
};
const SANTOS_DESTACADOS=[
  {id:'acutis',nombre:'San Carlo Acutis',sub:'Patrono de internet',img:'assets/img/santos/san_acutis.webp',bio:'Adolescente italiano (1991–2006), programador aficionado y devoto de la Eucaristía. Usó sus conocimientos de informática para catalogar milagros eucarísticos en un sitio web. Murió de leucemia fulminante a los 15 años. Fue canonizado en 2025.',oracion:'San Carlo Acutis, que usaste la tecnología para acercar a otros a Jesús, ruega por nosotros, para que sepamos poner lo que tenemos al servicio del bien. Amén.'},
  {id:'benito',nombre:'San Benito Abad',sub:'Patrono de Europa',img:'assets/img/santos/san_benito.webp',bio:'Monje italiano (c. 480–547), padre del monaquismo occidental y fundador de la Orden Benedictina. Escribió la Regla de San Benito, resumida en el lema "ora et labora" (reza y trabaja).',oracion:'San Benito, que buscaste a Dios en la oración y en el trabajo de cada día, ruega por nosotros, para que ordenemos nuestra vida en torno a Cristo. Amén.'},
  {id:'sebastian',nombre:'San Sebastián',sub:'Patrono de los atletas',img:'assets/img/santos/san_sebastian.webp',bio:'Soldado romano y mártir (siglo III), condenado a morir asaeteado por profesar su fe cristiana en tiempos de persecución. Sobrevivió a las flechas y fue martirizado poco después. Patrono de soldados, arqueros y atletas.',oracion:'San Sebastián, que no renunciaste a tu fe ni ante la persecución, ruega por nosotros, para que tengamos la fortaleza de sostener lo que creemos. Amén.'},
  {id:'maria',nombre:'Santísima Virgen María',sub:'Madre de la Iglesia',img:'assets/img/santos/virgen_maria.webp',bio:'Madre de Jesús, la primera y más grande de los santos. La tradición de la Iglesia la venera como Madre de Dios y Madre de la Iglesia, modelo de fe y de entrega total a la voluntad de Dios.',oracion:'Santa María, Madre de la Iglesia, ruega por nosotros, tus hijos, ahora y en la hora de nuestra muerte. Amén.'},
];
const SANTOS=[
  {m:'Enero',s:[{d:'1',n:'Santa María, Madre de Dios',nota:'Solemnidad'},{d:'2',n:'Santos Basilio y Gregorio Nacianceno',nota:'Doctores de la Iglesia'},{d:'6',n:'Epifanía del Señor',nota:'Solemnidad'},{d:'13',n:'San Hilario de Poitiers',nota:'Doctor de la Iglesia'},{d:'17',n:'San Antonio Abad',nota:'Padre del monaquismo oriental'},{d:'21',n:'Santa Inés',nota:'Mártir romana, patrona de la pureza'},{d:'24',n:'San Francisco de Sales',nota:'Doctor. Patrono de escritores y periodistas'},{d:'25',n:'Conversión de San Pablo',nota:'Fiesta'},{d:'28',n:'Santo Tomás de Aquino',nota:'Doctor Angélico. Patrono de estudiantes'},{d:'31',n:'San Juan Bosco',nota:'Fundador de los Salesianos'},]},
  {m:'Febrero',s:[{d:'2',n:'Presentación del Señor',nota:'Fiesta. La Candelaria'},{d:'3',n:'San Blas',nota:'Patrono de los enfermos de garganta'},{d:'5',n:'Santa Águeda',nota:'Mártir siciliana'},{d:'11',n:'Nuestra Señora de Lourdes',nota:'Apariciones de 1858 a Santa Bernadette'},{d:'14',n:'Santos Cirilo y Metodio',nota:'Apóstoles de los eslavos'},{d:'22',n:'Cátedra de San Pedro',nota:'Fiesta. Primado pontificio'},]},
  {m:'Marzo',s:[{d:'7',n:'Santas Perpetua y Felicidad',nota:'Mártires de Cartago'},{d:'17',n:'San Patricio',nota:'Apóstol de Irlanda'},{d:'19',n:'San José, Esposo de la Virgen',nota:'Solemnidad. Patrono de la Iglesia Universal'},{d:'25',n:'Anunciación del Señor',nota:'Solemnidad. Encarnación del Verbo'},]},
  {m:'Abril',s:[{d:'7',n:'San Juan Bautista de La Salle',nota:'Patrono de los educadores'},{d:'23',n:'San Jorge',nota:'Mártir. Patrono de Inglaterra y Cataluña'},{d:'29',n:'Santa Catalina de Siena',nota:'Doctora. Patrona de Europa e Italia'},]},
  {m:'Mayo',s:[{d:'1',n:'San José Obrero',nota:'Fiesta. Patrono de los trabajadores'},{d:'3',n:'Santos Felipe y Santiago',nota:'Apóstoles. Fiesta'},{d:'14',n:'San Matías',nota:'Apóstol elegido en lugar de Judas'},{d:'31',n:'Visitación de la Virgen María',nota:'Fiesta. María visita a Isabel'},]},
  {m:'Junio',s:[{d:'13',n:'San Antonio de Padua',nota:'Doctor. Patrono de los pobres y objetos perdidos'},{d:'21',n:'San Luis Gonzaga',nota:'Patrono de la juventud cristiana'},{d:'24',n:'Natividad de San Juan Bautista',nota:'Solemnidad'},{d:'29',n:'Santos Pedro y Pablo',nota:'Solemnidad. Pilares de la Iglesia'},]},
  {m:'Julio',s:[{d:'3',n:'Santo Tomás Apóstol',nota:'Fiesta. "Mi Señor y mi Dios"'},{d:'11',n:'San Benito',nota:'Patrono de Europa. Padre del monaquismo occidental'},{d:'22',n:'Santa María Magdalena',nota:'Fiesta. "Apóstola de los Apóstoles"'},{d:'25',n:'Santiago Apóstol',nota:'Fiesta. Patrono de España'},{d:'26',n:'Santos Joaquín y Ana',nota:'Padres de la Virgen María'},{d:'31',n:'San Ignacio de Loyola',nota:'Fundador de la Compañía de Jesús'},]},
  {m:'Agosto',s:[{d:'4',n:'San Juan María Vianney',nota:'Cura de Ars. Patrono de los párrocos'},{d:'6',n:'Transfiguración del Señor',nota:'Fiesta'},{d:'8',n:'Santo Domingo de Guzmán',nota:'Fundador de los Dominicos'},{d:'10',n:'San Lorenzo',nota:'Mártir. Diácono de Roma'},{d:'15',n:'Asunción de la Virgen María',nota:'Solemnidad'},{d:'28',n:'San Agustín de Hipona',nota:'Doctor. Patrono de teólogos'},{d:'29',n:'Martirio de San Juan Bautista',nota:'Memorial'},]},
  {m:'Septiembre',s:[{d:'8',n:'Natividad de la Virgen María',nota:'Fiesta'},{d:'14',n:'Exaltación de la Santa Cruz',nota:'Fiesta'},{d:'15',n:'Nuestra Señora de los Dolores',nota:'Memorial'},{d:'21',n:'San Mateo',nota:'Apóstol y Evangelista. Fiesta'},{d:'29',n:'Santos Miguel, Gabriel y Rafael',nota:'Arcángeles. Fiesta'},{d:'30',n:'San Jerónimo',nota:'Doctor. Traductor de la Biblia al latín (Vulgata)'},]},
  {m:'Octubre',s:[{d:'1',n:'Santa Teresa del Niño Jesús',nota:'Doctora. Patrona de las misiones'},{d:'2',n:'Santos Ángeles Custodios',nota:'Memorial'},{d:'4',n:'San Francisco de Asís',nota:'Patrono de la ecología'},{d:'7',n:'Nuestra Señora del Rosario',nota:'Memorial. Victoria de Lepanto 1571'},{d:'15',n:'Santa Teresa de Ávila',nota:'Doctora. Reformadora del Carmelo'},{d:'18',n:'San Lucas',nota:'Evangelista. Fiesta'},{d:'28',n:'Santos Simón y Judas Tadeo',nota:'Apóstoles. Fiesta'},]},
  {m:'Noviembre',s:[{d:'1',n:'Todos los Santos',nota:'Solemnidad'},{d:'2',n:'Conmemoración de los Fieles Difuntos',nota:'Por las almas del purgatorio'},{d:'4',n:'San Carlos Borromeo',nota:'Patrono de los seminaristas'},{d:'11',n:'San Martín de Tours',nota:'Patrón de los pobres y soldados'},{d:'22',n:'Santa Cecilia',nota:'Patrona de la música'},{d:'30',n:'San Andrés',nota:'Apóstol. Fiesta'},]},
  {m:'Diciembre',s:[{d:'3',n:'San Francisco Javier',nota:'Patrono de las misiones'},{d:'7',n:'San Ambrosio',nota:'Doctor. Patrono de Milán'},{d:'8',n:'Inmaculada Concepción',nota:'Solemnidad. Patrona de muchos países'},{d:'12',n:'Nuestra Señora de Guadalupe',nota:'Patrona de América'},{d:'13',n:'Santa Lucía',nota:'Mártir. Patrona de los enfermos de la vista'},{d:'25',n:'Natividad del Señor',nota:'Solemnidad'},{d:'26',n:'San Esteban',nota:'Primer mártir'},{d:'27',n:'San Juan Apóstol',nota:'El discípulo amado'},{d:'28',n:'Santos Inocentes',nota:'Mártires'},]},
];
const SALMOS=[
  {num:'Salmo 23',t:'El Señor es mi Pastor',s:'Para momentos de angustia y confianza',tx:'El Señor es mi pastor, nada me puede faltar.\nÉl me hace descansar en verdes praderas,\nme conduce a las aguas tranquilas\ny repara mis fuerzas;\nme guía por el recto sendero,\npor amor de su Nombre.\n\nAunque cruce por oscuras quebradas,\nno temeré ningún mal, porque tú estás conmigo:\ntu vara y tu bastón me infunden confianza.\n\nTú preparas ante mí una mesa,\nfrente a mis enemigos;\nunges con óleo mi cabeza\ny mi copa rebosa.\n\nTu bondad y tu gracia me acompañan\na lo largo de mi vida,\ny habitaré en la Casa del Señor\npor muy largo tiempo.'},
  {num:'Salmo 51',t:'Miserere — Misericordia, Señor',s:'Para buscar el perdón después de haber pecado',tx:'Ten piedad de mí, oh Dios, por tu bondad,\npor tu gran compasión, borra mi culpa.\nLávame bien de mi delito,\nlímpiame de mi pecado.\n\nPues yo reconozco mi culpa,\nmi pecado no se aparta de mí.\nContra ti, contra ti solo pequé,\ncometí la maldad que aborreces.\n\nCrea en mí, oh Dios, un corazón puro,\nrenuévame por dentro con espíritu firme;\nno me arrojes lejos de tu rostro,\nno me quites tu Espíritu Santo.\n\nDevuélveme la alegría de tu salvación,\nafiánzame con espíritu generoso.\n\nMi sacrificio es un espíritu quebrantado;\nun corazón quebrantado y humillado,\ntú no lo desprecias, oh Dios.'},
  {num:'Salmo 91',t:'Bajo la sombra del Altísimo',s:'Para cuando uno siente peligro o necesita protección',tx:'Tú que vives al amparo del Altísimo\ny resides a la sombra del Todopoderoso,\ndi al Señor: "Mi refugio y mi baluarte,\nmi Dios, en quien confío".\n\nÉl te librará de la red del cazador\ny de la peste perniciosa;\nsu brazo es escudo y coraza.\n\nNo temerás los terrores de la noche,\nni la flecha que vuela de día,\nni la peste que acecha en las tinieblas,\nni la plaga que devasta a pleno sol.\n\nNo te alcanzará ningún mal,\nninguna plaga se acercará a tu carpa,\nporque él te encomendó a sus ángeles\npara que te cuiden en todos tus caminos.\n\nÉl se entregó a mí, por eso, yo lo libraré;\nlo protegeré, porque conoce mi Nombre;\nme invocará, y yo le responderé.\nEstaré con él en el peligro.'},
  {num:'Salmo 139',t:'Señor, tú me sondeas y me conoces',s:'Para reflexionar sobre la presencia de Dios en nuestra vida',tx:'Señor, tú me sondeas y me conoces;\ntú sabes si me siento o me levanto,\nde lejos percibes lo que pienso,\nte das cuenta si camino o si descanso,\ny todos mis pasos te son familiares.\n\nAntes que la palabra esté en mi lengua,\ntú, Señor, la conoces plenamente;\nme rodeas por detrás y por delante\ny tienes puesta tu mano sobre mí.\n\n¿A dónde iré para estar lejos de tu espíritu?\n¿A dónde huiré de tu presencia?\nSi subo al cielo, allí estás tú;\nsi me tiendo en el abismo, estás presente.\n\nTú creaste mis entrañas,\nme plasmaste en el seno de mi madre:\nte doy gracias porque fui formado\nde manera tan admirable.'},
  {num:'Salmo 27',t:'El Señor es mi luz',s:'Para momentos de miedo y búsqueda de fortaleza',tx:'El Señor es mi luz y mi salvación,\n¿a quién temeré?\nEl Señor es el baluarte de mi vida,\n¿ante quién temblaré?\n\nUna sola cosa he pedido al Señor,\ny esto es lo que quiero:\nvivir en la Casa del Señor\ntodos los días de mi vida,\npara gozar de la dulzura del Señor\ny contemplar su Templo.\n\nMi corazón sabe que dijiste: "Busquen mi rostro".\nYo busco tu rostro, Señor, no lo apartes de mí.\n\nYo creo que contemplaré la bondad del Señor\nen la tierra de los vivientes.\nEspera en el Señor y sé fuerte;\nten valor y espera en el Señor.'},
  {num:'Salmo 103',t:'Bendice, alma mía, al Señor',s:'Para dar gracias y alabar la misericordia divina',tx:'Bendice al Señor, alma mía,\nque todo mi ser bendiga a su santo Nombre;\nbendice al Señor, alma mía,\ny nunca olvides sus beneficios.\n\nÉl perdona todas tus culpas\ny cura todas tus dolencias;\nrescata tu vida del sepulcro,\nte corona de amor y de ternura;\nél colma tu vida de bienes,\ny tu juventud se renueva como el águila.\n\nEl Señor es bondadoso y compasivo,\nlento para enojarse y de gran misericordia;\nno nos trata según nuestros pecados\nni nos paga conforme a nuestras culpas.\n\nCuanto se alza el cielo sobre la tierra,\nasí de inmenso es su amor por los que lo temen.\nComo la ternura de un padre con sus hijos\nes la ternura del Señor con los que le temen.'},
];
